### ISSUE TITLE
GenFSM not found

### ISSUE THREAD

**Issue by Thomas-Ahn** [smpallen99/speak_ex#1]
I'm new to elixir and encounter GenFSM error on speak_ex compilation where ex_ami has a dependency, however, ex_ami and gen_fsm are compiled okay individually. It looks there is some issue with elixir environment, but I couldn't figure out.

Erlang version: Erlang/OTP 19 [erts-8.3]
elixir: 1.4.1 and Elixir 1.5.0-dev 

== Compilation error on file lib/ex_ami/client.ex ==
** (CompileError) lib/ex_ami/client.ex:3: module GenFSM is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/ex_ami/client.ex:3: ExAmi.Client (module)

could not compile dependency :ex_ami, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_ami", update it with "mix deps.update ex_ami" or clean it with "mix deps.clean ex_ami"

**Comment by smpallen99** [comment]
Has been fixed. Removed the gen_fsm dependency from this project, and updated it in ex_ami
